import "./globals.css";
import { Lato } from "next/font/google";
import "@/styles/buttons.css";
import "@/styles/inputs.css";
import "@/styles/select.css";
import "@/styles/tables.css";
import "@/styles/response.css";
import "@/styles/texts.css";
import "@/styles/typography.css";

const spaceGrotesk = Lato({
  subsets: ["latin-ext"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata = {
  title: "Next Spring",
  description: "Generated by create next app, Perfected by spring initializr.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>{children}</body>
    </html>
  );
}
